import { getScannerRoute } from '@shopgate/pwa-common-commerce/scanner/helpers';
import { SCANNER_TYPE_BARCODE } from '@shopgate/pwa-core/constants/Scanner';

// TODO: TYPE_QR CODE support needed in first version?

export const SCANNER_SCOPE = 'sp-loyalty';
export const SCANNER_SCOPE_POINTS = 'sp-loyalty-points';
export const SCANNER_ROUTE = getScannerRoute(SCANNER_SCOPE, SCANNER_TYPE_BARCODE);
export const SCANNER_ROUTE_POINTS = getScannerRoute(SCANNER_SCOPE_POINTS, SCANNER_TYPE_BARCODE);

export const LOYALTY_ROUTE = '/loyalty';
export const LOYALTY_INIT_ACCOUNT_ROUTE = '/loyalty/init';
export const LOYALTY_POINTS_HISTORY_ROUTE = '/loyalty/points/history';
export const LOYALTY_COUPONS_ROUTE = '/loyalty/coupons';
export const LOYALTY_COUPONS_TAB_ROUTE = `${LOYALTY_COUPONS_ROUTE}/:tab`;

export const REQUEST_INIT_ACCOUNT = 'REQUEST_INIT_ACCOUNT';
export const SUCCESS_INIT_ACCOUNT = 'SUCCESS_INIT_ACCOUNT';
export const ERROR_INIT_ACCOUNT = 'ERROR_INIT_ACCOUNT';

export const RECEIVE_LOYALTY_ACCOUNT_INFO = 'RECEIVE_LOYALTY_ACCOUNT_INFO';
export const REQUEST_LOYALTY_ACCOUNT_INFO = 'REQUEST_LOYALTY_ACCOUNT_INFO';
export const ERROR_LOYALTY_ACCOUNT_INFO = 'ERROR_LOYALTY_ACCOUNT_INFO';

export const RECEIVE_LOYALTY_POINTS_HISTORY = 'RECEIVE_LOYALTY_POINTS_HISTORY';
export const REQUEST_LOYALTY_POINTS_HISTORY = 'REQUEST_LOYALTY_POINTS_HISTORY';
export const ERROR_LOYALTY_POINTS_HISTORY = 'ERROR_LOYALTY_POINTS_HISTORY';

export const RECEIVE_LOYALTY_COUPONS = 'RECEIVE_LOYALTY_COUPONS';
export const REQUEST_LOYALTY_COUPONS = 'REQUEST_LOYALTY_COUPONS';
export const ERROR_LOYALTY_COUPONS = 'ERROR_LOYALTY_COUPONS';

export const RECEIVE_LOYALTY_USER_COUPONS = 'RECEIVE_LOYALTY_USER_COUPONS';
export const REQUEST_LOYALTY_USER_COUPONS = 'REQUEST_LOYALTY_USER_COUPONS';
export const ERROR_LOYALTY_USER_COUPONS = 'ERROR_LOYALTY_USER_COUPONS';

export const SUCCESS_LOYALTY_ENROLL_COUPON = 'REQUEST_LOYALTY_ENROLL_COUPON';
export const ERROR_LOYALTY_ENROLL_COUPON = 'ERROR_LOYALTY_ENROLL_COUPON';

export const SUCCESS_LOYALTY_ENROLL_POINTS = 'SUCCESS_LOYALTY_ENROLL_POINTS';
export const ERROR_LOYALTY_ENROLL_POINTS = 'ERROR_LOYALTY_ENROLL_POINTS';

